# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/warranty_db
spring.datasource.username=postgres
spring.datasource.password=kanak@123

# JPA & Hibernate Settings (Validate schema against Flyway)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kanikaborkar@gmail.com
spring.mail.password=xvdp cpeu wapm mbjf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Notification Target Email (where the alerts will be delivered)
app.mail.alert-recipient=kanikaborkar@gmail.com